print("unc test below")
wait(1)
print("unc test below")
wait(1)
print("unc test below")
wait(1)
print("unc test below")
wait(1)
print("unc test below")
wait(1)
wait(5)
loadstring(game:HttpGet("https://github.com/SmilezReal/Executor-Tests/raw/refs/heads/main/UncTest.lua",true))()
wait(5)
print("sunc test below")
wait(1)
print("sunc test below")
wait(1)
print("sunc test below")
wait(1)
print("sunc test below")
wait(1)
print("sunc test below")
wait(1)
wait(5)
loadstring(game:HttpGet("https://github.com/SmilezReal/Executor-Tests/raw/refs/heads/main/sUncTest.lua",true))()
wait(5)
print("vuln test below")
wait(1)
print("vuln test below")
wait(1)
print("vuln test below")
wait(1)
print("vuln test below")
wait(1)
print("vuln test below")
wait(1)
wait(5)
loadstring(game:HttpGet("https://github.com/SmilezReal/Executor-Tests/raw/refs/heads/main/VulnTest.lua",true))()
wait(1)
print("if any of these test didnt work. please re-execute the script. if the issues still persist. your executor does not support this script.")
